# Generated by Django 4.1.7 on 2023-03-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_author_books_publisher_alter_books_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateField(),
        ),
    ]
